# Site settings
title: Vladan's blog
#email:
description: > # this means to ignore newlines until "baseurl:"
  Blog of my work in Mozilla's Firefox Performance team
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.vladan.org" # the base hostname & protocol for your site
twitter_username: djeric3
github_username:  vdjeric
timezone: America/Toronto


# Build settings
markdown: kramdown

# Plugins
gems:
  - jekyll-sitemap
# Uncomment this dependency once this issue is fixed (very soon): https://github.com/sparklemotion/nokogiri/issues/1256
#  - jemoji

