# Site settings
title: Vladan's blog
#email:
description: > # this means to ignore newlines until "baseurl:"
  Blog of my work in Mozilla's Firefox Performance team
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://blog.vladan.org" # the base hostname & protocol for your site
twitter_username: djeric3
github_username:  vdjeric
timezone: America/Toronto


# Build settings
markdown: kramdown

# Plugins
plugins:
  - jekyll-sitemap

# Setting this replaces Jekyll's default exclude list, so it repeats those entries
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .bundle

